#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Robert Sander <gurubert@gurubert.de>
#
# Released under GPLv2

apacheconfig = """<VirtualHost {domain}:443>
	ServerAdmin webmaster@{domain}
	ServerName {domain}

	DocumentRoot {userhome}/public_html
	RewriteEngine	On
	RewriteRule	^/$	/cgi-bin/ezmlm [L,R=permanent]

	ScriptAlias /cgi-bin {userhome}/cgi-bin/

	<Location "/">
		AuthName "{domain} ezmlm"
		AuthType Basic
		AuthBasicProvider file
		AuthUserFile {userhome}/htpasswd
		require valid-user
	</Location>

	ErrorLog ${APACHE_LOG_DIR}/{domain}-error.log

	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/{domain}-access.log combined

	SSLEngine on
        SSLCertificateFile    /etc/ssl/certs/{domain}.pem
        SSLCertificateKeyFile /etc/ssl/private/{domain}.key
        <Directory {userhome}/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
"""

ezmlmwebrc = """$LIST_DIR = "$HOME_DIR/lists";
$MAIL_ADDRESS_PREFIX = "";
$LANGUAGE_DIR = "/usr/share/ezmlm-web/lang";
$TEMPLATE_DIR = "/usr/share/ezmlm-web/template";
$UNSAFE_RM = 0;
$ALIAS_USER = "alias";
$QMAIL_BASE = $Mail::Ezmlm::QMAIL_BASE . '/control';
$MAIL_DOMAIN = "%s";
$PRETTY_NAMES = 1;
$FILE_UPLOAD = 1;
$DEFAULT_OPTIONS = "ABDFgHiJkLMNOPQRSTUWx";
$HTML_TITLE = "ezmlm-web for {domain}";
$HTML_CSS_COMMON = "/ezmlm-web/default.css";
$HTML_CSS_COLOR = "/ezmlm-web/color-blue-gray.css";
$HTML_LANGUAGE = "de";
$DEBUG = 0;
"""

virtualdomains = '/var/qmail/control/virtualdomains'
rcpthosts = '/var/qmail/control/rcpthosts'
qmailsend = '/service/qmail-send'

import argparse
import os
import pwd
import sys
import subprocess
import htpasswd

parser = argparse.ArgumentParser(description='Create or remove mailing list user for ezmlm.')
parser.add_argument('username', help='Username for the virtual domain')
parser.add_argument('--add' , '-a', metavar='domain', help='Domain name for the virtual domain')
parser.add_argument('--delete' , '-d', action='store_true')
args = parser.parse_args()

if args.add:
    try:
        pwd.getpwnam(args.username)
        print "User %s already exists" % args.username
        sys.exit(1)
    except KeyError:
        pass
    domain = args.add

    if os.path.isfile(rcpthosts):
        for line in open(rcpthosts).readlines():
            if line.find(domain) > -1:
                print "Domain already configured: %s" % line
                sys.exit(1)

    # add domain:username to /var/qmail/control/virtualdomains
    v = open(virtualdomains, 'a')
    v.write("%s:%s\n" % (domain, args.username))
    v.close()

    # add domain to /var/qmail/control/rcpthosts
    r = open(rcpthosts, 'a')
    r.write("%s\n" % domain)
    r.close()

    print subprocess.check_output(['/usr/sbin/useradd', '-m', args.username])

    userinfo = pwd.getpwnam(args.username)

    print subprocess.check_output(['/usr/bin/svc', '-h', qmailsend])

    for dir in ["public_html", "lists", "cgi-bin"]:
        os.mkdir(os.path.join(userinfo.pw_dir, dir), 0755)
        os.chown(os.path.join(userinfo.pw_dir, dir), userinfo.pw_uid, userinfo.pw_gid)

    print subprocess.check_output(['/usr/bin/ezmlm-web-make-suid', args.username, os.path.join(userinfo.pw_dir, "cgi-bin", "ezmlm")])

    
    

if args.delete:
    try:
        userinfo = pwd.getpwnam(args.username)
    except KeyError:
        print "Unable to find user %s" % args.username
        sys.exit(1)

TODO = """
Einmalig:

cp /usr/share/doc/ezmlm-web/examples/apache.conf.dist /etc/apache2/conf.d/ezmlm
a2enmod rewrite
a2enmod ssl

# /etc/init.d/apache2 restart 

Site Creation:



useradd -m username
qmail-ctl restart
mkdir /home/username/public_html
mkdir /home/username/lists
mkdir /home/username/cgi-bin
ezmlm-web-make-suid username /home/username/cgi-bin/ezmlm
htpasswd -cs /home/username/htpasswd webadmin

add apache config in sites-available & sites-enabled

SSL:

PASSWORD=`makepasswd  --chars=20`

openssl req -new -x509 -keyout /etc/ssl/private/{domain}.key.enc -out /etc/ssl/certs/{domain}.crt -days 3600 -newkey rsa:4096 -passout env:PASSWORD -subj "C=DE/ST=Berlin/L=Berlin/O=Heinlein Support GmbH/OU=Hosting/CN={domain}/emailAddress=support@heinlein-hosting.de"
openssl rsa -in /etc/ssl/private/{domain}.key.enc -out /etc/ssl/private/{domain}.key -passin env:PASSWORD

/etc/init.d/apache2 restart

Site Deletion:

remove domain from /var/qmail/control/virtualdomains & /var/qmail/control/rcpthosts
remove apache config from sites-enabled

qmail-ctl restart
/etc/init.d/apache2 restart

"""
