#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Robert Sander <gurubert@gurubert.de>
#
# Released under GPLv2


apacheconfig = """<VirtualHost {domain}:443>
	ServerAdmin webmaster@{domain}
	ServerName {domain}

	DocumentRoot {userhome}/public_html
	RewriteEngine	On
	RewriteRule	^/$	/cgi-bin/ezmlm [L,R=permanent]

	ScriptAlias /cgi-bin {userhome}/cgi-bin/

	<Location "/">
		AuthName "{domain} ezmlm"
		AuthType Basic
		AuthBasicProvider file
		AuthUserFile {userhome}/htpasswd
		require valid-user
	</Location>

	ErrorLog ${APACHE_LOG_DIR}/{domain}-error.log

	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/{domain}-access.log combined

	SSLEngine on
        SSLCertificateFile    /etc/ssl/certs/{domain}.pem
        SSLCertificateKeyFile /etc/ssl/private/{domain}.key
        <Directory {userhome}/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
"""

ezmlmwebrc = """$LIST_DIR = "$HOME_DIR/lists";
$MAIL_ADDRESS_PREFIX = "";
$LANGUAGE_DIR = "/usr/share/ezmlm-web/lang";
$TEMPLATE_DIR = "/usr/share/ezmlm-web/template";
$UNSAFE_RM = 0;
$ALIAS_USER = "alias";
$QMAIL_BASE = $Mail::Ezmlm::QMAIL_BASE . '/control';
$MAIL_DOMAIN = "%s";
$PRETTY_NAMES = 1;
$FILE_UPLOAD = 1;
$DEFAULT_OPTIONS = "ABDFgHiJkLMNOPQRSTUWx";
$HTML_TITLE = "ezmlm-web for {domain}";
$HTML_CSS_COMMON = "/ezmlm-web/default.css";
$HTML_CSS_COLOR = "/ezmlm-web/color-blue-gray.css";
$HTML_LANGUAGE = "de";
$DEBUG = 0;
"""

TODO = """
Einmalig:

cp /usr/share/doc/ezmlm-web/examples/apache.conf.dist /etc/apache2/conf.d/ezmlm
a2enmod rewrite
a2enmod ssl

# /etc/init.d/apache2 restart 

Site Creation:

add IP to interfaces

add domain:username to /var/qmail/control/virtualdomains
add domain to /var/qmail/control/rcpthosts

qmail-ctl restart

useradd -m username
mkdir /home/username/public_html
mkdir /home/username/lists
mkdir /home/username/cgi-bin
ezmlm-web-make-suid username /home/username/cgi-bin/ezmlm
htpasswd -cs /home/username/htpasswd webadmin

add apache config in sites-available & sites-enabled

SSL:

PASSWORD=`makepasswd  --chars=20`

openssl req -new -x509 -keyout /etc/ssl/private/{domain}.key.enc -out /etc/ssl/certs/{domain}.crt -days 3600 -newkey rsa:4096 -passout env:PASSWORD -subj "C=DE/ST=Berlin/L=Berlin/O=Heinlein Support GmbH/OU=Hosting/CN={domain}/emailAddress=support@heinlein-hosting.de"
openssl rsa -in /etc/ssl/private/{domain}.key.enc -out /etc/ssl/private/{domain}.key -passin env:PASSWORD

/etc/init.d/apache2 restart

Site Deletion:

remove domain from /var/qmail/control/virtualdomains & /var/qmail/control/rcpthosts
remove apache config from sites-enabled

qmail-ctl restart
/etc/init.d/apache2 restart

"""
